apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scale-test-app
  template:
    metadata:
      labels:
        app: scale-test-app
    spec:
      containers:
        - name: scale-test-app-container
          image: shestera/scaletestapp
          resources:
            limits:
              memory: "15Mi"
            requests:
              memory: "10Mi"
          ports:
            - containerPort: 8080